project_id = "klxyilxprlzhxnwjzcvv"

[functions.create-user-with-role]
verify_jwt = true

[functions.auto-mark-sessions]
verify_jwt = false

[functions.get-consent-data]
verify_jwt = false

[functions.submit-consent-form]
verify_jwt = false

[functions.send-consent-form]
verify_jwt = true

[functions.issue-nfse]
verify_jwt = true

[functions.send-nfse-email]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.export-patient-data]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.send-whatsapp-reply]
verify_jwt = true

[functions.download-whatsapp-media]
verify_jwt = true

[functions.check-consent-expiry]
verify_jwt = false
