project_id = "klxyilxprlzhxnwjzcvv"

[functions.auto-mark-sessions]
verify_jwt = false

[functions.issue-nfse]
verify_jwt = true

[functions.send-nfse-email]
verify_jwt = false

[functions.export-patient-data]
verify_jwt = true
